# Generated by Django 5.1.4 on 2025-02-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_atleta',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
