# Generated by Django 5.1.1 on 2024-10-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
