# Generated by Django 5.1.1 on 2024-10-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_estoque_movimentacaoestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_ultima_movimentacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='data_movimentacao',
            field=models.DateTimeField(null=True),
        ),
    ]
