# Generated by Django 5.1.4 on 2025-01-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_remove_produto_categoria_produto_marca_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='marca_id',
            new_name='marca',
        ),
    ]
