# Generated by Django 5.1.5 on 2025-02-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_rename_marca_id_produto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_venda_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
