# Generated by Django 5.1.4 on 2025-02-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custo_mensal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='CustoMensal',
        ),
    ]
