# Generated by Django 5.1.4 on 2025-02-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_mensal', '0002_rename_marca_customensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customensal',
            name='anomes',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customensal',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customensal',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
