# Generated by Django 5.1.4 on 2025-02-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_mensal', '0003_customensal_anomes_alter_customensal_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customensal',
            name='recorrente',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
