# Generated by Django 5.1.4 on 2025-03-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_mensal', '0004_customensal_recorrente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customensal',
            name='anomes',
        ),
        migrations.AddField(
            model_name='customensal',
            name='dat_fim',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customensal',
            name='dat_ini',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
