# Generated by Django 5.1.4 on 2025-03-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_mensal', '0005_remove_customensal_anomes_customensal_dat_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customensal',
            name='dat_fim',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customensal',
            name='dat_ini',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
