# Generated by Django 5.1.4 on 2025-03-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custo_mensal', '0006_alter_customensal_dat_fim_alter_customensal_dat_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customensal',
            name='dat_fim',
            field=models.DateTimeField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customensal',
            name='dat_ini',
            field=models.DateTimeField(max_length=30, null=True),
        ),
    ]
