# Generated by Django 5.1.3 on 2024-12-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotacao',
        ),
    ]
