# Generated by Django 5.1.3 on 2024-12-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
