# Generated by Django 5.1.4 on 2025-01-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_bairro_pedido_cep_pedido_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='is_estoque_externo',
            field=models.BooleanField(default=False),
        ),
    ]
