# Generated by Django 5.1.4 on 2025-01-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_itempedido_is_estoque_externo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataPedido',
            field=models.DateTimeField(),
        ),
    ]
