# Generated by Django 5.1.5 on 2025-02-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='precoCusto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
